export const DATA = [
  {
    id: 1,
    name: "Blue Sneakers",
    href: "#",
    imageSrc: "/images/sneaker1.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 50,
    brand: "Nike",
  },
  {
    id: 2,
    name: "Yellow Shoes",
    href: "#",
    imageSrc: "/images/sneaker2.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 40,
    brand: "Nike",
  },
  {
    id: 3,
    name: "White Shoes",
    href: "#",
    imageSrc: "/images/sneaker3.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 50,
    brand: "Nike",
  },
  {
    id: 4,
    name: "Green Shoes",
    href: "#",
    imageSrc: "/images/sneaker4.jpg",
    imageAlt: "Front of men's Basic Tee in black.",
    price: 60,
    brand: "Nike",
  },
];
